.github/workflows/nuget_windows.yml
src/.idea/.idea.Asv.Common/.idea/vcs.xml

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204776694698757

Add test running step

---

.github/workflows/no_test_nuget_windows.yml

Add workflow without a test step
Asana: https://app.asana.com/0/1203851531040615/1204851102803575/f

ci: add no test worflow

---

src/Asv.Common.Test/GeoPointLatitudeTest.cs
src/Asv.Common.Test/GeoPointLongitudeTest.cs
src/Asv.Common/Other/Angle.cs
src/Asv.Common/Other/GeoPoint/GeoPointLatitude.cs
src/Asv.Common/Other/GeoPoint/GeoPointLongitude.cs

Updated the longitude and latitude parsing and printing for the Angle, GeoPointLongitude, GeoPointLatitude classes in Asv.Common. The changes allow recognizing decimal values as degree, minute and second in the parsing methods. Adjustments in printing methods contain handling absolute degrees and allowing degrees to keep a negative sign. Besides, a new test was added for short values in DMS tests.
Asana: https://app.asana.com/0/1203851531040615/1205166500713016/f

feat(common): improve longitude and latitude parsing and printing

---

src/Asv.Common.Test/AngleMsTest.cs
src/Asv.Common.Test/AngleTest.cs
src/Asv.Common/Other/AngleMs.cs

Added a new AngleMs class under Asv.Common, which handles the parsing and validation of angle values given in both degrees and minute seconds format. Also included new test cases in AngleMsTest under Asv.Common.Test to validate the AngleMs functionality. This was necessary to enable more precise representation and manipulation of angle values in specific application contexts. Certain modifications were also made in the AngleTest class for name uniformity.
Asana: https://app.asana.com/0/1203851531040615/1205715715897878/f

feat: add AngleMs class and its test cases

---

src/Asv.Common.Test/AngleDmTest.cs
src/Asv.Common/Other/AngleDm.cs
src/Asv.Common/RS.Designer.cs
src/Asv.Common/RS.resx
src/Asv.Common/RS.ru.resx

In this commit, support for AngleDM format has been added to the Asv.Common library and associated unit testing. This new functionality will provide additional flexibility for users who need to work with angles in different formats. `AngleDm` class and the `AngleDmTest` were added, they provide parsing, conversion, and validation utilities for angles in degrees and minutes format. Error messages for invalid input were also added to resource (.resx) files for localization purposes.
Asana: https://app.asana.com/0/1203851531040615/1205774880091085/f

feat: add support for AngleDM format in Asv.Common library

---

src/Asv.Common.Test/GeoPointLatitudeTest.cs
src/Asv.Common.Test/GeoPointLongitudeTest.cs
src/Asv.Common/Other/GeoPoint/GeoPointLatitude.cs
src/Asv.Common/Other/GeoPoint/GeoPointLongitude.cs

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207435459410130

format 45:54.454S

---

src/Asv.IO.Test/Streams/Ports/Crypto/AesTest.cs
src/Asv.IO/Streams/Ports/Crypto/AES/AesCryptoPort.cs
src/Asv.IO/Streams/Ports/PortBase.cs

Asana:
https://app.asana.com/0/1203851531040615/1207238121409943/f

AesCryptoPort improvement

---

.github/workflows/release-debug-version.yml
.github/workflows/release-pre-version.yml
src/Asv.Cfg/InMemory/InMemoryConfiguration.cs

Make 2 new workflows and change globs for tags
Asana: https://app.asana.com/0/1203851531040615/1208209955231563/f

feat: update workflows, add Composition to workflows

---

src/Asv.Cfg.Test/ZipJsonConfigurationTests.cs

Asana: https://app.asana.com/0/1203851531040615/1208234015896061/f

fix: make all tests use Path class for path generation

---

src/Asv.IO.Test/ULog/ULogSynchronizationMessageToken.Tests.cs
src/Asv.IO/ULog/Tokens/Synchronization/ULogSynchronizationMessageToken.cs
src/Asv.IO/ULog/ULog.cs
src/Asv.IO/ULog/ULogReader.cs

Asana: https://app.asana.com/0/1203851531040615/1208271533462295/f

feat(ulog): add sync message token and tests

---

src/Asv.IO.Test/ULog/ULogLoggedStringMessageToken.Tests.cs
src/Asv.IO/ULog/Tokens/LoggedString/ULogLoggedStringMessageToken.cs
src/Asv.IO/ULog/ULog.cs
src/Asv.IO/ULog/ULogReader.cs

asana: https://app.asana.com/0/1203851531040615/1208271533186873/f

feat(ulog): add logged string message token and tests

---

src/Asv.IO.Test/ULog/ULogUnsubscriptionMessageToken.Tests.cs
src/Asv.IO/Asv.IO.csproj.DotSettings
src/Asv.IO/ULog/Tokens/Unsubscription/ULogUnsubscriptionMessageToken.cs
src/Asv.IO/ULog/ULog.cs
src/Asv.IO/ULog/ULogReader.cs

Asana: https://app.asana.com/0/1203851531040615/1208271533186869/f

feat(ulog): add ULogUnsubscriptionMessageToken and tests

---

src/Asv.IO.Test/ULog/ULogDropoutMessageToken.Tests.cs
src/Asv.IO/Asv.IO.csproj.DotSettings
src/Asv.IO/ULog/Tokens/Dropout/ULogDropoutMessageToken.cs
src/Asv.IO/ULog/ULog.cs
src/Asv.IO/ULog/ULogReader.cs

Asana: https://app.asana.com/0/1203851531040615/1208271533462297/f

feat(ulog): add ULogDropoutMessageToken and tests

---

src/Asv.IO.Test/ULog/ULogLoggedDataMessageToken.Tests.cs
src/Asv.IO/Asv.IO.csproj.DotSettings
src/Asv.IO/ULog/Tokens/LoggedData/ULogLoggedDataMessageToken.cs
src/Asv.IO/ULog/ULog.cs

Asana:
https://app.asana.com/0/1203851531040615/1208271533186871/f

add: ULog logged-data-token with tests

---

.github/workflows/release-pre-version.yml

Asana: https://app.asana.com/0/1203851531040615/1208533851305527/f

fix: remove --prerelease flags from the prerelease workflow

---

src/Asv.IO.Test/Protocol/Connection/ProtocolConnectionTests.cs

Asana: https://app.asana.com/0/1203851531040615/1208910371095941/f

test(protocol-connection): add tests for ProtocolConnection

---

src/Asv.Common.Shell/Commands/TcpTest.cs
src/Asv.IO.Test/Protocols/TcpPortComplexTest.cs

Asana: https://app.asana.com/0/1203851531040615/1208922515913871/f

test(tcp-port): add tests for tcp-test command and unit test

---

src/Asv.IO.Test/Protocol/Connection/Virtual/VirtualPortTest.cs

Asana: https://app.asana.com/0/1203851531040615/1208922515913871/f
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208953236198038

test(virtual-connection): add tests for IStatistic and connection

---

src/Asv.IO.Test/Protocol/Connection/Virtual/VirtualConnectionTest.cs

Asana: https://app.asana.com/0/1203851531040615/1209032966851364/f

test(virtual-connection): remove cancellation token lifetime

---

src/Asv.Cfg.Test/Json/ZipJsonVersionedFileTest.cs

asana: https://app.asana.com/0/1203851531040615/1208681153408539/f

tests(ZipJsonVersionedFile): add tests for ctor

---

.github/workflows/release-action.yml
.github/workflows/release-debug-version.yml
src/.idea/.idea.Asv.Common/.idea/AndroidProjectSystem.xml
src/Asv.Cfg.Test/Asv.Cfg.Test.csproj
src/Asv.Cfg/Asv.Cfg.csproj
src/Asv.Common.Shell/Asv.Common.Shell.csproj
src/Asv.Common.Test/Asv.Common.Test.csproj
src/Asv.Common/Asv.Common.csproj
src/Asv.Composition.Test/Asv.Composition.Test.csproj
src/Asv.Composition/Asv.Composition.csproj
src/Asv.IO.Test/Asv.IO.Test.csproj
src/Asv.IO/Asv.IO.csproj
src/Directory.Build.props

Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210902613481121?focus=true

feat: update dotnet core version to 9

---

src/Asv.Common.Test/Other/FloatingPointComparerTest.cs
src/Asv.Common.Test/Other/GeoPoint/GeoPointTest.cs
src/Asv.Common/Other/FloatingPointComparer.cs
src/Asv.Common/Units/GeoPoint/GeoPoint.cs
src/Directory.Build.props

Asana: https://app.asana.com/1/1200746044236722/project/1210705292501615/task/1211182046710619

fix: use approximate equality in GeoPoint
